name: Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install deps
      run: npm ci

    - name: Build
      run: npm run build

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download build
      uses: actions/download-artifact@v2
      with:
        name: build
    - name: Transfer build files to server
      uses: appleboy/scp-action@master
      with:
        host: 89.208.211.100
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        source: "./build/*"
        target: "/home/ubuntu/frontend"
